### ISSUE TITLE
Create Successful But Rolled Back

### ISSUE THREAD

**Issue by anguillanneuf** [awslabs/aws-rekognition-workshop-twitter-bot#1]
I followed the instructions to create a new stack but it seems that there were still some issues to be ironed out. S3 buckets were not created. 

![20170621](https://user-images.githubusercontent.com/9518298/27404452-1fbf2246-569c-11e7-83ae-4de3f21b339f.PNG)

**Comment by ranman** [comment]
Can you delete that stack and try again now? There was an issue with the code earlier where it relied on the aws cli instead of wget but a fix got pushed in c99caf5d2e5a4679d88e126bcdcbf544d2acf0d7

**Comment by anguillanneuf** [comment]
It works now. Thanks!
